name: Tag Version

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  create_tag:
    name: Create Tag
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Setup Git
      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # Step 3: Determine version type based on commit message
      - name: Determine version type
        id: version_type
        run: |
          # Default to patch update
          VERSION_TYPE="patch"
          
          # Get the latest commit message
          COMMIT_MSG=$(git log -1 --pretty=%B)

          # Prioritize major change detection
          if echo "$COMMIT_MSG" | grep -qi "breaking change" || echo "$COMMIT_MSG" | grep -qi "major change"; then
            VERSION_TYPE="major"
          elif echo "$COMMIT_MSG" | grep -qi "new feature" || echo "$COMMIT_MSG" | grep -qi "enhancement"; then
            VERSION_TYPE="minor"
          elif echo "$COMMIT_MSG" | grep -qi "bug fix" || echo "$COMMIT_MSG" | grep -qi "fix"; then
            VERSION_TYPE="patch"
          fi

          echo "version_type=$VERSION_TYPE" >> $GITHUB_ENV

      # Step 4: Create a new tag using the GitHub Tag Action
      - name: Create Tag Version
        uses: hennejg/github-tag-action@v4.3.1
        with:
          tag_prefix: "v"
          version_type: ${{ env.version_type }}
          dry_run: false
          release_description: "Automated versioning based on commit messages"
